### ISSUE TITLE
Use resources not labels [-4]

### ISSUE THREAD

**Issue by skodapetr** [ZuzaBohatova/DataCube#3]
```
    ns1:county "Benešov"^^xsd:string ;
    ns1:fieldOfCare "Adiktolog, sexuologie, návykové nemoci, psychiatrie"^^xsd:string ;
    ns1:region "Středočeský kraj"^^xsd:string .
```
Zde měla být použitá IRI těch krajů/okresů/..., nikoliv názvy.

**Comment by skodapetr** [comment]
Ještě tam chybí labely pro ty resources, tedy třeba ns1:Plzenskykraj by měl mít skos:prefLabel ve kterém bude "Plzeňský kraj"

**Comment by ZuzaBohatova** [comment]
> Ještě tam chybí labely pro ty resources, tedy třeba ns1:Plzenskykraj by měl mít skos:prefLabel ve kterém bude "Plzeňský kraj"

přidala jsem je tam, snad už to bude ok
